version: '3.3'

services:
  db:
    build: ./mysql/
    image: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose

  backend:
    depends_on:
      - db
    build: ./flask/
    image: flaskcompose
    restart: always
    ports:
      - "5000:5000"
    networks:
      - dockercompose

networks:
  dockercompose: